/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import de.berlinskylarks.appconfigclient.apis.DefaultAPI
import de.berlinskylarks.appconfigclient.models.ApplicationContext
import de.berlinskylarks.appconfigclient.models.ConfigurationDTO
import de.berlinskylarks.appconfigclient.models.FeatureFlagDTO

class DefaultAPITest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultAPI
        //val apiInstance = DefaultAPI()

        // to test getConfigs
        should("test getConfigs") {
            // uncomment below to test getConfigs
            //val context : ApplicationContext =  // ApplicationContext | Optional application context to filter for.
            //val result : kotlin.collections.List<ConfigurationDTO> = apiInstance.getConfigs(context)
            //result shouldBe ("TODO")
        }

        // to test getFlags
        should("test getFlags") {
            // uncomment below to test getFlags
            //val excludedConfigID : kotlin.String = 123e4567-e89b-12d3-a456-426655440000 // kotlin.String | Optional UUID to filter out flags already linked to this configuration.
            //val result : kotlin.collections.List<FeatureFlagDTO> = apiInstance.getFlags(excludedConfigID)
            //result shouldBe ("TODO")
        }

    }
}
