/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import de.berlinskylarks.appconfigclient.models.ConfigurationDTOApiURLS

class ConfigurationDTOApiURLSTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigurationDTOApiURLS
        //val modelInstance = ConfigurationDTOApiURLS()

        // to test the property `bsmURL`
        should("test bsmURL") {
            // uncomment below to test the property
            //modelInstance.bsmURL shouldBe ("TODO")
        }

        // to test the property `cmsURL`
        should("test cmsURL") {
            // uncomment below to test the property
            //modelInstance.cmsURL shouldBe ("TODO")
        }

        // to test the property `dpURL`
        should("test dpURL") {
            // uncomment below to test the property
            //modelInstance.dpURL shouldBe ("TODO")
        }

    }
}
