/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import de.berlinskylarks.appconfigclient.models.ConfigurationDTO
import de.berlinskylarks.appconfigclient.models.ApplicationContext
import de.berlinskylarks.appconfigclient.models.ConfigurationDTOApiURLS
import de.berlinskylarks.appconfigclient.models.FlagWithStatusDTO

class ConfigurationDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigurationDTO
        //val modelInstance = ConfigurationDTO()

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `applicationContext`
        should("test applicationContext") {
            // uncomment below to test the property
            //modelInstance.applicationContext shouldBe ("TODO")
        }

        // to test the property `apiURLS`
        should("test apiURLS") {
            // uncomment below to test the property
            //modelInstance.apiURLS shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `flagRelations`
        should("test flagRelations") {
            // uncomment below to test the property
            //modelInstance.flagRelations shouldBe ("TODO")
        }

    }
}
