/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import de.berlinskylarks.appconfigclient.models.FlagWithStatusDTO
import de.berlinskylarks.appconfigclient.models.FeatureFlagDTO

class FlagWithStatusDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FlagWithStatusDTO
        //val modelInstance = FlagWithStatusDTO()

        // to test the property `flag`
        should("test flag") {
            // uncomment below to test the property
            //modelInstance.flag shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

    }
}
