/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import de.berlinskylarks.appconfigclient.models.HealthCheck

class HealthCheckTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthCheck
        //val modelInstance = HealthCheck()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
