/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.apis

import de.berlinskylarks.appconfigclient.models.ApplicationContext
import de.berlinskylarks.appconfigclient.models.ConfigurationDTO
import de.berlinskylarks.appconfigclient.models.FeatureFlagDTO

import de.berlinskylarks.appconfigclient.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class DefaultAPI : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * List all configurations
     * Provides a list of all configurations with their associated feature flags.
     * @param context Optional application context to filter for. (optional)
     * @return kotlin.collections.List<ConfigurationDTO>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getConfigs(context: ApplicationContext? = null): HttpResponse<kotlin.collections.List<ConfigurationDTO>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        context?.apply { localVariableQuery["context"] = listOf("${ context.value }") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/configs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetConfigsResponse>().map { value }
    }

    @Serializable(GetConfigsResponse.Companion::class)
    private class GetConfigsResponse(val value: List<ConfigurationDTO>) {
        companion object : KSerializer<GetConfigsResponse> {
            private val serializer: KSerializer<List<ConfigurationDTO>> = serializer<List<ConfigurationDTO>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetConfigsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetConfigsResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * List all feature flags
     * Provides an API list of feature flags, optionally filtering out those already linked to a configuration.
     * @param excludedConfigID Optional UUID to filter out flags already linked to this configuration. (optional)
     * @return kotlin.collections.List<FeatureFlagDTO>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getFlags(excludedConfigID: kotlin.String? = null): HttpResponse<kotlin.collections.List<FeatureFlagDTO>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        excludedConfigID?.apply { localVariableQuery["excludedConfigID"] = listOf("$excludedConfigID") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/flags",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetFlagsResponse>().map { value }
    }

    @Serializable(GetFlagsResponse.Companion::class)
    private class GetFlagsResponse(val value: List<FeatureFlagDTO>) {
        companion object : KSerializer<GetFlagsResponse> {
            private val serializer: KSerializer<List<FeatureFlagDTO>> = serializer<List<FeatureFlagDTO>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetFlagsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetFlagsResponse(serializer.deserialize(decoder))
        }
    }

}
