/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models

import de.berlinskylarks.appconfigclient.models.ApplicationContext
import de.berlinskylarks.appconfigclient.models.ConfigurationDTOApiURLS
import de.berlinskylarks.appconfigclient.models.FlagWithStatusDTO

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param updatedAt 
 * @param name 
 * @param applicationContext 
 * @param apiURLS 
 * @param id 
 * @param description 
 * @param flagRelations 
 */
@Serializable

data class ConfigurationDTO (

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "applicationContext") @Required val applicationContext: ApplicationContext,

    @SerialName(value = "apiURLS") @Required val apiURLS: ConfigurationDTOApiURLS,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "flagRelations") val flagRelations: kotlin.collections.Map<kotlin.String, FlagWithStatusDTO>? = null

) {


}

