/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.berlinskylarks.appconfigclient.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bsmURL 
 * @param cmsURL 
 * @param dpURL 
 */
@Serializable

data class ConfigurationDTOApiURLS (

    @SerialName(value = "bsmURL") @Required val bsmURL: kotlin.String,

    @SerialName(value = "cmsURL") @Required val cmsURL: kotlin.String,

    @SerialName(value = "dpURL") @Required val dpURL: kotlin.String

) {


}

